include/openglwidget.h
src/openglwidget.cpp

`QImage` removed, exceptions for shader adding and compiling eded, custom deleter for `QOpenGL*` objects.

Merge with opengl branch

---

src/openglwidget.cpp

Emit pixelViewrectChanged (e.g. update bars) before redraw image

---

src/openglwidget.cpp
src/scrollzoomarea.cpp

Fix fit to window (again)

---

src/main.cpp
src/openglwidget.cpp

- Remove version specifier
- Add precision specifiers for ES
Fix #23

Adapt GLSL code to work with OpenGL ES

---

README.md

Homebrew caskroom
Packages from releases

Add info about Homebrew and installation

---

include/levelswidget.h
src/levelswidget.cpp

Scientific spin box

---

src/opengltexture.cpp

Under specific circumstances the image may be corrupted due unsuitable
row alignment value. The default alignment value is 4 bytes.

Fix issue with row alignment

---

CMakeLists.txt
include/fits.h
include/mainwindow.h
include/openglerrors.h
include/opengltexture.h
include/openglwidget.h
include/scrollzoomarea.h
src/fits.cpp
src/mainwindow.cpp
src/openglerrors.cpp
src/opengltexture.cpp
src/openglwidget.cpp
src/scrollzoomarea.cpp

(Re)load FITS in the same window

---

CMakeLists.txt
include/fits.h
include/mainwindow.h
include/mousepositionwidget.h
include/openglerrors.h
include/openglwidget.h
include/pixel.h
include/utils/exception.h
include/utils/optional.h
src/fits.cpp
src/mainwindow.cpp
src/mousepositionwidget.cpp
src/openglwidget.cpp
src/pixel.cpp
src/utils/exception.cpp
test/utils/optional.cpp

Add status bar with image pixel position of cursor and value of corresponding pixel

---

include/mainwindow.h
src/mainwindow.cpp

Add autorefresh

---

include/levelswidget.h
src/levelswidget.cpp

Add more level controls

---

src/mainwindow.cpp

Remove dock widget shortcuts

---

test/openglplane.cpp

Redo TestOpenGLPlane

---

include/abstractopenglplan.h
include/abstractopengltexture.h
include/levelswidget.h
include/openglplan.h
include/openglwidget.h
src/abstractopenglplan.cpp
src/abstractopengltexture.cpp
src/levelswidget.cpp
src/mainwindow.cpp
src/openglplan.cpp
src/opengltexture.cpp
src/openglwidget.cpp

This PR is mostly for review and discussion.

Introduce OpenGLPlan framework (Part I)

---

include/scientificspinbox.h
src/scientificspinbox.cpp

Fix ScientificSpinBox text edition

---

CMakeLists.txt

Add Qt version status message for CMakeLists.txt

---

include/application.h
src/application.cpp

Also check the result in Application constructor.
Close #91

Return number of opened files from openFile()

---

include/abstractopenglplan.h
include/openglfeatures.h
include/openglplan.h
include/opengltexture.h
src/abstractopenglplan.cpp
src/main.cpp
src/openglfeatures.cpp
src/openglplan.cpp
src/openglplanfactory.cpp
src/opengltexture.cpp

Add OpenGL 3.x support

---

include/abstractopengltexture.h
src/abstractopengltexture.cpp
src/opengltexture.cpp
src/openglwidget.cpp

Fix Fips on big-endian systems

---

.travis.yml

- Cache homebrew data for macOS build
- Use minimal image for Linux (Docker) builds

Speed up Travis builds

---

.travis.yml

Keep Qt 5.9 LTS and Qt 5.6 LTS

Add Qt 5.12

---

include/application.h
src/application.cpp

Do not crash app when broken file is dropped via macOS Dock

---

README.md

Add bibtex for Astronomy and Computing paper

---

include/mainwindow.h
src/application.cpp
src/mainwindow.cpp

Drag and drop files

---

.travis.yml

Do not fail Travis build when transfer.sh is down

---

include/application.h
src/application.cpp

Check that at least one instance is started correctly

---

.appveyor.yml

Update deploy auth_token in .appveyor.yml

---

.travis.yml

Fix #156 
Check these GUI features before merge:

Fix up macOS Travis build

---

.github/workflows/tests.yml

Check these GUI features before merge:

qt6 CI for macOS
